# Custom NanoAOD v12, Run3, 2022, postEE
#
# "post" refers to the era in 2022 after the ECAL Endcap (EE) adjustment
#  which is commonly denoted as "Run3Summer22EE" in DAS.
#
# Links:
#   - https://gitlab.cern.ch/cms-nanoAOD/nanoaod-doc/-/wikis/Releases/NanoAODv12
#   - https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis
#   - https://docs.google.com/presentation/d/1F4ndU7DBcyvrEEyLfYqb29NGkBPs20EAnBxe_l7AEII/edit#slide=id.g289f499aa6b_2_52

# cmssw setup
# from https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRun3Analysis#Recipes_for_Run3Summer22_and_Run
# CMSSW version should be CMSSW_13_0_13 maybe?
cmssw_version: CMSSW_13_0_19
scram_arch: el9_amd64_gcc11
cmssw_env_name: nanogen
sandbox_script: cmssw_nanogen.sh

# arguments for cmsDriver.py that creates the cmsRun config
global_tag:
  # https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/130X_mcRun3_2022_realistic_postEE_v6
  mc: 130X_mcRun3_2022_realistic_postEE_v6
  # https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/130X_dataRun3_v4
  # from Marcel: v2 supersedes the recommended v2 GT and the proposed 130X_dataRun3_PromptAnalysis_v1
  # from Nathan: really? 1) should be v4 in the comment, 2) nowhere to see that this is superseded
  # TODO:
  # recommendation is still 130X_dataRun3_PromptAnalysis_v1 according to presentation,
  # might be 130X_dataRun3_Prompt_HcalSiPM_v1 because of the Hcal SiPM issue
  # https://cms-talk.web.cern.ch/t/gt-offline-update-of-hcal-offline-sipmcharacteristics-for-run3-re-reco/32748
  # or 130X_dataRun3_v4 if this also contains the Hcal SiPM fix for 2022 postEE
  # waiting for answer in https://cms-talk.web.cern.ch/t/nanoaod-custom-production-for-2022-post-ee-data/49043/1
  # TODO: 2: era E still has 2022 pre tag, so it should be 130X_dataRun3_v4
  data: 130X_dataRun3_PromptAnalysis_v1
era:
  mc: &era Run3
  data: *era

# postfix for produced nano datasets in the cms-store-like path
campaign_postfix: NanoAODv12UHH

# references to dataset and nano configs
dataset_config: datasets_22post.yaml
nano_config: nano_run3_v12.yaml
