# Custom NanoAOD v14, Run3, 2024
#
# Links:
#   - https://gitlab.cern.ch/cms-nanoAOD/nanoaod-doc/-/wikis/Releases/NanoAODv15
#   - https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis
#   - https://docs.google.com/presentation/d/1EHxQcWzw8IxPgCn8hm1prwSP-EktFtiuaEzH8WkQNVY/edit?slide=id.g36971dee1d1_0_0#slide=id.g36971dee1d1_0_0

# cmssw setup
# from https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRun3Analysis#Recipes_for_Run3Summer23_and_Run
# CMSSW version should be at least CMSSW_15_0_2 (but 150X)
cmssw_version: CMSSW_15_0_10_patch3
scram_arch: el9_amd64_gcc12
cmssw_env_name: nanogen
sandbox_script: cmssw_nanogen.sh

# arguments for cmsDriver.py that creates the cmsRun config
global_tag:
  # see https://cms-higgs-leprare.docs.cern.ch/#common-hleprare-nanoaod-skims
  mc: auto:phase1_2024_realistic
  # should resolve to 150X_mcRun3_2024_realistic_v2, see
  # https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/150X_mcRun3_2024_realistic_v2
  data: auto:run3_data
  # used to resolve to 150X_dataRun3_v2, see
  # https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/150X_dataRun3_v2
era:
  mc: &era Run3_2024
  data: *era

# lumi mask for data
# https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis?rev=172#Year_2024
lumi_mask: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions24/Cert_Collisions2024_378981_386951_Golden.json

# postfix for produced nano datasets in the cms-store-like path
campaign_postfix: NanoAODv15UHH

# references to dataset and nano configs
dataset_config: datasets_24.yaml
nano_config: nano_run3_v15.yaml
