# Custom NanoAOD v12, Run3, 2022, postEE
#
# "post" refers to the era in 2022 after the ECAL Endcap (EE) adjustment
#  which is commonly denoted as "Run3Summer22EE" in DAS.
#
# Links:
#   - https://gitlab.cern.ch/cms-nanoAOD/nanoaod-doc/-/wikis/Releases/NanoAODv12
#   - https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis
#   - https://docs.google.com/presentation/d/1F4ndU7DBcyvrEEyLfYqb29NGkBPs20EAnBxe_l7AEII/edit#slide=id.g289f499aa6b_2_52

# cmssw setup
# from https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRun3Analysis#Recipes_for_Run3Summer22_and_Run
cmssw_version: CMSSW_13_0_19
scram_arch: el9_amd64_gcc11
cmssw_env_name: nanogen
sandbox_script: cmssw_nanogen.sh

# arguments for cmsDriver.py that creates the cmsRun config
global_tag:
  # https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/130X_mcRun3_2022_realistic_postEE_v6
  mc: 130X_mcRun3_2022_realistic_postEE_v6
  # from https://cms-talk.web.cern.ch/t/nanoaod-custom-production-for-2022-post-ee-data/49043/2 :
  # Use: https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/130X_dataRun3_PromptAnalysis_v1
  # which is the recommended GT for 2022 postEE data
  data: 130X_dataRun3_PromptAnalysis_v1
era:
  mc: &era Run3
  data: *era

# lumi mask for data
# https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis?rev=161#Year_2022
lumi_mask: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json

# postfix for produced nano datasets in the cms-store-like path
campaign_postfix: NanoAODv12UHH

# references to dataset and nano configs
dataset_config: datasets_22post.yaml
nano_config: nano_run3_v12.yaml
