# Custom NanoAOD v12, Run2, 2018
#
# Links:
#   - https://gitlab.cern.ch/cms-nanoAOD/nanoaod-doc/-/wikis/Releases/NanoAODv12
#   - https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2Analysis

# cmssw setup
cmssw_version: CMSSW_13_0_19
scram_arch: el9_amd64_gcc11
cmssw_env_name: nanogen
sandbox_script: cmssw_nanogen.sh

# arguments for cmsDriver.py that creates the cmsRun config
global_tag:
  mc: auto:phase1_2018_realistic
  data: auto:run2_data
era:
  mc: &era Run2_2018,run2_nanoAOD_106Xv2
  data: *era

# postfix for produced nano datasets in the cms-store-like path
campaign_postfix: NanoAODv12UHH

# references to dataset and nano configs
dataset_config: datasets_18.yaml
nano_config: nano_run2_v12.yaml
