# Custom NanoAOD v14, Run3, 2023, postBPix
#
# "pre" refers to the era in 2023 after the barrel pixel (BPix) adjustment
#  which is commonly denoted as "Run3Summer23BPix" in DAS.
#
# Links:
#   - https://gitlab.cern.ch/cms-nanoAOD/nanoaod-doc/-/wikis/Releases/NanoAODv14
#   - https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis
#   - https://docs.google.com/presentation/d/1TjPem5jX0fzqvTGl271_nQFoVBabsrdrO0i8Qo1uD5E/edit?usp=sharing

# cmssw setup
# from https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRun3Analysis#Recipes_for_Run3Summer23_and_Run
# CMSSW version should be at least CMSSW_14_0_6_patch1 (but 140X)
cmssw_version: CMSSW_14_0_21_patch1
scram_arch: el9_amd64_gcc12
cmssw_env_name: nanogen_taupog
sandbox_script: cmssw_nanogen.sh

# arguments for cmsDriver.py that creates the cmsRun config
global_tag:
  # see https://cms-higgs-leprare.docs.cern.ch/#common-hleprare-nanoaod-skims
  mc: auto:phase1_2023_realistic_postBPix
  # use to resolve to 140X_mcRun3_2023_realistic_postBPix_v3, see
  # https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_mcRun3_2023_realistic_postBPix_v3
  data: auto:run3_data
  # used to resolve to 140X_dataRun3_v14, see
  # https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_dataRun3_v14
era:
  mc: &era Run3_2023
  data: *era

# lumi mask for data
# https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis?rev=172#Year_2023
lumi_mask: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions23/Cert_Collisions2023_366442_370790_Golden.json

# postfix for produced nano datasets in the cms-store-like path
campaign_postfix: NanoAODv14UHH

# references to dataset and nano configs
dataset_config: datasets_23post.yaml
nano_config: nano_run3_v14.yaml
