# nano customonization hook to be injected into the cmsRun config
customization:
  module: nanogen.customizations.default
  function: customize_v12_uhh
  arguments: {}

# objects to by bypassed in skimming process and copied as is
bypass:
  - LuminosityBlocks
  - Runs

# skimming configs
skim:
  - input_tree: Events
    output_tree: Events
    selection: "return true;"
    column_filters:
      # drop some object collections alltogether
      - drop ^n?CaloMET.*$
      - drop ^n?CorrT1METJet.*$
      - drop ^n?TkMET.*$
      - drop ^n?FsrPhoton.*$
      - drop ^n?GenDressedLepton.*$
      - drop ^n?GenIsolatedPhoton.*$
      - drop ^n?GenProton.*$
      - drop ^n?IsoTrack.*$
      - drop ^n?L1.*$
      - drop ^n?LowPtElectron.*$
      - drop ^n?OtherPV.*$
      - drop ^n?SoftActivityJet.*$
