name: Lint and test

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt

      - name: Lint 🔍
        run: |
          export PYTHONPATH="${PWD}/modules/law:${PYTHONPATH}"
          flake8 nanogen

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt

      - name: Typecheck 🥊
        run: |
          export PYTHONPATH="${PWD}/modules/law:${PYTHONPATH}"
          mypy nanogen
